### ISSUE TITLE
[NOT-10] Weeknotes update 09/29/2023

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/weeknotes#10]
### Topic 1

CI pipelines often interact with components from multiple cloud providers. Consider an example of an integration that you run on GitHub Actions infrastructure. The test case needs to put a file in Google Cloud's Storage bucket. One way to authenticate your Github Actions job is to place your credentials file in the repository secrets.

It gives Github access to your bucket in the Google Cloud forever. However, giving full access to your resources to a third-party infrastructure provider is not a good security practice. If your GitHub account gets compromised, the attacker can access your Google Cloud bucket, too.

A better approach is to use the [OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform) protocol. OIDC allows your GitHub Actions workflows to access Google Cloud resources using a GCP IAM policy. It also doesn't require storing the GCP credentials as long-lived GitHub secrets. The [auth](https://github.com/google-github-actions/auth) Github Actions module uses the [workload identity federation](https://cloud.google.com/iam/docs/workload-identity-federation) offered by GCP to fetch a short-lived JWT token. This token gives temporary access to a Google Cloud resource you need for a particular workflow. To implement it in your Github Action workflows, you can follow this [guide](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#adding-a-google-cloud-workload-identity-provider)

Here is an example of a simple GitHub Actions workflow that authenticates on behalf of the developer and lists all GCP services.

```
name: List services in GCP
on:
  pull_request:
    branches:
      - main
permissions: 
  id-token: write ### <= This is required for requesting the JWT

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest 
    steps:
    - id: 'auth' ### <= fetch ODIC token for this workflow
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: '<your gcp identity pool provider>'
          service_account: '<your gcp service account>'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
```

### Topic 2

\[write-up\]

<sub>From [SyncLinear.com](https://synclinear.com) | [NOT-10](https://linear.app/tableland/issue/NOT-10/weeknotes-update-09292023)</sub>
